# Generated by Django 5.0.14 on 2026-08-13 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('intervention_created', 'Intervention créée'), ('intervention_assigned', 'Intervention affectée'), ('intervention_started', 'Intervention démarrée'), ('intervention_closed', 'Intervention clôturée'), ('alert_acknowledged', 'Alerte prise en charge'), ('alert_resolved', 'Alerte résolue'), ('equipment_created', 'Équipement ajouté'), ('equipment_updated', 'Équipement modifié'), ('sensor_created', 'Capteur ajouté'), ('alert_triggered', 'Alerte déclenchée automatiquement')], max_length=30)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=30)),
                ('target_reference', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'), models.Index(fields=['action', '-created_at'], name='activity_ac_action_4b3c59_idx')],
            },
        ),
    ]
