# Generated by Django 5.0.14 on 2026-08-12 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('intervention_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive')], default='corrective', max_length=12)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='planned', max_length=12)),
                ('description', models.TextField()),
                ('report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='equipment.equipment')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='interventio_status_1066b0_idx'), models.Index(fields=['equipment', '-created_at'], name='interventio_equipme_3ba348_idx'), models.Index(fields=['technician', 'status'], name='interventio_technic_7c648d_idx')],
            },
        ),
    ]
