# Generated by Django 5.0.14 on 2026-08-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_interventionrequest_maintenancechecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancechecklist',
            name='intervention',
            field=models.ForeignKey(blank=True, help_text='If set, this checklist is specific to this intervention only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='interventions.intervention'),
        ),
    ]
