-- backend/recreate_all_tables.sql
-- Recrée uniquement les tables spécifiques à l'application users.
-- Les tables gérées automatiquement par Django sont laissées intactes.

BEGIN;

CREATE TABLE IF NOT EXISTS users_userprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport varchar(128) NOT NULL DEFAULT '',
    role_title varchar(128) NOT NULL DEFAULT '',
    user_id bigint NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_systemadmin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(150) NOT NULL UNIQUE,
    email varchar(254) NOT NULL DEFAULT '',
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    password varchar(128) NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS user_plain_password (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL DEFAULT '',
    user_id bigint NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
);

-- Les tables Django gérées automatiquement (auth_user, django_content_type, admin, sessions, etc.) sont conservées.
-- Seules les tables spécifiques à l'application users sont définies ici.

COMMIT;
