-- backend/reset_app_tables.sql
-- Réinitialise uniquement les tables spécifiques à l'application users.
-- Les tables gérées automatiquement par Django (auth, contenttypes, admin, sessions) restent intactes.

BEGIN;

DROP TABLE IF EXISTS user_plain_password CASCADE;
DROP TABLE IF EXISTS users_systemadmin CASCADE;
DROP TABLE IF EXISTS users_userprofile CASCADE;

CREATE TABLE IF NOT EXISTS users_userprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport varchar(128) NOT NULL DEFAULT '',
    role_title varchar(128) NOT NULL DEFAULT '',
    user_id bigint NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_systemadmin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(150) NOT NULL UNIQUE,
    email varchar(254) NOT NULL DEFAULT '',
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    password varchar(128) NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS user_plain_password (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL DEFAULT '',
    user_id bigint NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
);

COMMIT;
