# Generated by Django 5.0.14 on 2026-08-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)'), ('vibration', 'Vibration (mm/s)'), ('pressure', 'Pressure (bar)'), ('power', 'Power Consumption (kW)'), ('airflow', 'Air Flow (m³/h)'), ('voltage', 'Voltage (V)'), ('current', 'Current (A)'), ('runtime', 'Runtime (h)')], max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('min_normal', models.FloatField(help_text='Minimum normal value')),
                ('max_normal', models.FloatField(help_text='Maximum normal value')),
                ('alert_threshold', models.FloatField(help_text='Value that triggers an alert')),
                ('critical_threshold', models.FloatField(help_text='Value that triggers a critical alert')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulty', 'Faulty')], default='active', max_length=10)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='equipment.equipment')),
            ],
            options={
                'ordering': ['equipment', 'sensor_type'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__d03b31_idx'), models.Index(fields=['timestamp'], name='sensors_sen_timesta_8162d3_idx')],
            },
        ),
    ]
