# Generated by Django 5.0.14 on 2026-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='host',
            field=models.CharField(blank=True, help_text='IP or hostname (e.g., 192.168.1.50)', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Port number (e.g., 502)', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='protocol',
            field=models.CharField(choices=[('modbus_tcp', 'Modbus TCP'), ('mqtt', 'MQTT'), ('opcua', 'OPC-UA'), ('http', 'HTTP API')], default='modbus_tcp', max_length=15),
        ),
        migrations.AddField(
            model_name='sensor',
            name='register',
            field=models.CharField(blank=True, help_text='Register address or MQTT topic (e.g., 40001 or hvac/temp)', max_length=200),
        ),
    ]
